## Process this file with automake to produce Makefile.in
desktopdir = $(datadir)/applications
desktop_DATA = procedural-visualizer-tool.desktop

mimedir = $(datadir)/mime/packages
mime_DATA = application-x-procedural-visualizer-tool-project.xml

EXTRA_DIST = $(desktop_DATA) $(mime_DATA) \
	procedural_visualizer_tool.desktop.in \
	procedural_visualizer_tool.desktop.in.in
