#!/usr/bin/env python3
"""Maintain Qt catalogs using only Python's standard library and Qt Linguist."""

import argparse
from collections import Counter
from html.parser import HTMLParser
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
CATALOGS = ROOT / "translations"
RELEASED_LOCALES = CATALOGS / "released-locales.txt"
PLACEHOLDER = re.compile(r"%(?:L?[1-9][0-9]?|L?n)")
LOCALE_CODE = re.compile(r"[a-z]{2,3}(?:_[A-Za-z0-9]+)*")
LABEL_FILES = ["core.cpp", "composite.cpp", "config_io.cpp", "frame_renderer.cpp"]
LUPDATE_EXCLUDED_GUI_SOURCES = {"macos_video_export.mm"}


def released_locales():
    locales = []
    for number, raw_line in enumerate(
            RELEASED_LOCALES.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if not LOCALE_CODE.fullmatch(line):
            raise ValueError(f"released-locales.txt:{number}: invalid Qt locale: {line}")
        if line == "en":
            raise ValueError(f"released-locales.txt:{number}: English is implicit")
        if line in locales:
            raise ValueError(f"released-locales.txt:{number}: duplicate locale: {line}")
        locales.append(line)
    return locales


def desktop_locale(locale):
    """Convert the Qt spelling used by catalogs to desktop-entry spelling."""
    parts = locale.split("_")
    language = parts.pop(0)
    script = next((part for part in parts if len(part) == 4 and part.isalpha()), None)
    territory = next((part for part in parts
                      if (len(part) == 2 and part.isalpha())
                      or (len(part) == 3 and part.isdigit())), None)
    result = language + (f"_{territory}" if territory else "")
    return result + (f"@{script}" if script else "")


def platform_metadata_errors(locale):
    errors = []
    desktop_code = desktop_locale(locale)
    desktop_sections = {}
    section = None
    desktop_path = ROOT / "script/procedural-visualizer-tool.desktop"
    for raw_line in desktop_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
            desktop_sections.setdefault(section, {})
        elif section and "=" in line and not line.startswith("#"):
            key, value = line.split("=", 1)
            desktop_sections[section][key] = value
    main = desktop_sections.get("Desktop Entry", {})
    action = desktop_sections.get("Desktop Action NewWindow", {})
    for key in ("Name", "GenericName", "Comment", "Keywords"):
        localized = f"{key}[{desktop_code}]"
        if not main.get(localized, "").strip():
            errors.append(f"desktop entry lacks {localized}")
    action_name = f"Name[{desktop_code}]"
    if not action.get(action_name, "").strip():
        errors.append(f"desktop NewWindow action lacks {action_name}")

    mime_path = ROOT / "script/application-x-procedural-visualizer-tool-project.xml"
    mime_root = ET.parse(mime_path).getroot()
    bcp47 = locale.replace("_", "-")
    xml_language = "{http://www.w3.org/XML/1998/namespace}lang"
    mime_namespace = "{http://www.freedesktop.org/standards/shared-mime-info}"
    comments = {
        node.get(xml_language): (node.text or "").strip()
        for node in mime_root.findall(f".//{mime_namespace}comment")
    }
    if not comments.get(bcp47):
        errors.append(f"MIME comment lacks xml:lang={bcp47}")

    macos_path = CATALOGS / "macos" / f"{bcp47}.lproj" / "InfoPlist.strings"
    if not macos_path.exists():
        errors.append(f"macOS metadata is missing: {macos_path.relative_to(ROOT)}")
    else:
        macos = macos_path.read_text(encoding="utf-8")
        for key in ("NSMicrophoneUsageDescription", "NSLocalNetworkUsageDescription"):
            match = re.search(rf'^"{key}"\s*=\s*"(.+)";$', macos, re.M)
            if not match or not match.group(1).strip():
                errors.append(f"macOS metadata lacks {key} for {locale}")
    return errors


def renderer_labels():
    labels = set()
    for name in LABEL_FILES:
        source = (ROOT / "src" / name).read_text(encoding="utf-8")
        for body in re.findall(r"const char\* \w+_name\([^)]*\)\s*\{(.*?)^\}",
                               source, re.M | re.S):
            labels.update(re.findall(r'"([^"\\]*)"', body))
    lines = [
        "// Generated by scripts/translations.py labels; do not translate here.",
        "// Renderer/API names stay stable. Only their GUI presentation is translated.",
        "#ifndef PVT_RENDERER_LABELS_H", "#define PVT_RENDERER_LABELS_H",
        "#include <QCoreApplication>", "#include <QString>", "",
        "inline QString renderer_label(const char* source) {",
        '    return QCoreApplication::translate("RendererLabels", source);', "}", "",
        "[[maybe_unused]] inline constexpr const char* kRendererLabels[] = {",
    ]
    lines += [f'    QT_TRANSLATE_NOOP("RendererLabels", "{label}"),' for label in sorted(labels)]
    return "\n".join(lines + ["};", "#endif", ""])


class Markup(HTMLParser):
    """Reject broken rich text and changed links while allowing word reordering."""
    VOID = {"br", "hr", "img", "meta", "link", "input", "wbr"}

    def __init__(self, value):
        super().__init__(convert_charrefs=True)
        self.stack = []
        self.tags = Counter()
        self.links = Counter()
        self.feed(value)
        self.close()
        if self.stack:
            raise ValueError("unclosed rich-text tag")

    def handle_starttag(self, tag, attrs):
        self.tags[tag] += 1
        if tag not in self.VOID:
            self.stack.append(tag)
        self.links.update(value for key, value in attrs if key in {"href", "src"})

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in self.VOID:
            self.handle_endtag(tag)

    def handle_endtag(self, tag):
        if tag in self.VOID:
            return
        if not self.stack or self.stack.pop() != tag:
            raise ValueError("mismatched rich-text tag")


def gui_sources():
    # Qt 6.10 lupdate mistakes nested Objective-C message expressions (`[[...`)
    # for C++ attributes. The excluded backend has no Qt-translatable strings.
    return sorted(
        str(path) for path in (ROOT / "gui").iterdir()
        if path.suffix in {".cpp", ".h", ".mm"}
        and path.name not in LUPDATE_EXCLUDED_GUI_SOURCES)


def plural_form_count(locale, lupdate):
    """Ask the active Qt version how many plural forms this locale needs.

    Qt owns the plural-rule data used by both Linguist and QTranslator.  Keeping
    a handwritten CLDR subset here would eventually reject a valid Qt locale or
    accept the wrong number of forms after a Qt update.  Generate a tiny,
    disposable catalog instead so validation always follows the build's Qt.
    """
    with tempfile.TemporaryDirectory(prefix="pvt-plural-probe-") as temporary:
        temporary = Path(temporary)
        source = temporary / "plural_probe.cpp"
        catalog = temporary / "plural_probe.ts"
        source.write_text(
            '#include <QObject>\n'
            'void plural_probe() { (void)QObject::tr("%n item(s)", nullptr, 1); }\n',
            encoding="utf-8")
        result = subprocess.run(
            [lupdate, str(source), "-silent", "-locations", "none",
             "-source-language", "en", "-target-language", locale,
             "-no-obsolete", "-ts", str(catalog)],
            text=True, capture_output=True, cwd=ROOT)
        if result.returncode or result.stderr.strip() or not catalog.exists():
            detail = (result.stdout + result.stderr).strip()
            raise ValueError(f"Qt plural-form probe failed for {locale}: {detail}")
        root = ET.parse(catalog).getroot()
        messages = [message for context in root.findall("context")
                    for message in context.findall("message")
                    if message.get("numerus") == "yes"]
        if len(messages) != 1:
            raise ValueError(f"Qt plural-form probe produced {len(messages)} plural messages for {locale}")
        translation = messages[0].find("translation")
        forms = [] if translation is None else translation.findall("numerusform")
        if not forms:
            raise ValueError(f"Qt plural-form probe produced no plural forms for {locale}")
        return len(forms)


def add_catalogs(locales, lupdate):
    """Create catalogs together, without leaving a partial batch on failure."""
    paths = [(locale, CATALOGS / f"pvt_{locale}.ts") for locale in locales]
    existing = [str(path) for _, path in paths if path.exists()]
    if existing:
        raise ValueError("catalog already exists: " + ", ".join(existing))
    temporary_paths = []
    try:
        for locale, path in paths:
            # Keep the temporary file beside the final catalog. That preserves
            # useful relative source locations in the generated TS document.
            with tempfile.NamedTemporaryFile(
                    mode="w", encoding="utf-8", dir=CATALOGS,
                    prefix=f".pvt_{locale}.", suffix=".ts", delete=False) as temporary:
                temporary.write(
                    '<?xml version="1.0" encoding="utf-8"?>\n'
                    '<!DOCTYPE TS>\n'
                    f'<TS version="2.1" language="{locale}" sourcelanguage="en">\n</TS>\n')
                temporary_path = Path(temporary.name)
            temporary_paths.append((temporary_path, path))
            result = subprocess.run(
                [lupdate, *gui_sources(), "-locations", "relative",
                 "-source-language", "en", "-target-language", locale,
                 "-no-obsolete", "-ts", str(temporary_path)],
                text=True, capture_output=True, cwd=ROOT)
            if result.returncode or result.stderr.strip():
                detail = (result.stdout + result.stderr).strip()
                raise ValueError(f"Qt extraction failed or warned for {locale}: {detail}")
            root = ET.parse(temporary_path).getroot()
            if root.get("language") != locale or root.get("sourcelanguage") != "en":
                raise ValueError(f"Qt generated inconsistent locale metadata for {locale}")
        appeared = [str(path) for _, path in paths if path.exists()]
        if appeared:
            raise ValueError("catalog appeared during generation: " + ", ".join(appeared))
        for temporary_path, path in temporary_paths:
            temporary_path.replace(path)
    finally:
        for temporary_path, _ in temporary_paths:
            temporary_path.unlink(missing_ok=True)


def check(lupdate=None):
    errors = []
    try:
        release_locales = released_locales()
    except (OSError, ValueError) as error:
        errors.append(str(error))
        release_locales = []
    if (ROOT / "gui/renderer_labels.h").read_text(encoding="utf-8") != renderer_labels():
        errors.append("Renderer labels changed: run scripts/translations.py labels, then pvt_update_translations")
    template = ET.parse(CATALOGS / "pvt_en.ts").getroot()

    def key(context, message):
        return (context.findtext("name"), message.findtext("source", ""),
                message.findtext("comment", ""), message.get("numerus", "no"))

    source_keys = {key(c, m) for c in template.findall("context") for m in c.findall("message")}
    plural_counts = {}

    def expected_plural_forms(locale):
        if not lupdate:
            raise ValueError(
                "plural forms need Qt lupdate validation; pass --lupdate /path/to/lupdate")
        if locale not in plural_counts:
            plural_counts[locale] = plural_form_count(locale, lupdate)
        return plural_counts[locale]

    if lupdate:
        with tempfile.TemporaryDirectory(prefix="pvt-catalog-check-") as temporary:
            extracted = Path(temporary) / "pvt_en.ts"
            result = subprocess.run(
                [lupdate, *gui_sources(), "-silent", "-locations", "none", "-source-language", "en",
                 "-target-language", "en", "-ts", str(extracted)],
                text=True, capture_output=True, cwd=ROOT)
            if result.returncode or result.stderr.strip():
                errors.append("Qt extraction failed or warned: " + result.stdout + result.stderr)
            elif extracted.exists():
                fresh = ET.parse(extracted).getroot()
                fresh_keys = {key(c, m) for c in fresh.findall("context") for m in c.findall("message")}
                if fresh_keys != source_keys:
                    errors.append("English template is stale: run pvt_update_translations")
    coverage = {}
    for path in sorted(CATALOGS.glob("pvt_*.ts")):
        try:
            tree = ET.parse(path).getroot()
            code = path.stem[4:]
            if tree.get("language") != code or tree.get("sourcelanguage") != "en":
                raise ValueError("language metadata must match filename and English source")
            seen = set()
            finished = 0
            total = 0
            for context in tree.findall("context"):
                for message in context.findall("message"):
                    translation = message.find("translation")
                    if translation is not None and translation.get("type") in {"vanished", "obsolete"}:
                        continue
                    item_key = key(context, message)
                    if item_key in seen:
                        raise ValueError(f"duplicate message: {item_key[:2]}")
                    seen.add(item_key)
                    total += 1
                    if translation is None or translation.get("type") == "unfinished":
                        continue
                    source = message.findtext("source", "")
                    forms = translation.findall("numerusform") if message.get("numerus") == "yes" else [translation]
                    if not forms:
                        raise ValueError(f"missing plural forms: {source[:80]}")
                    if message.get("numerus") == "yes":
                        expected = expected_plural_forms(code)
                        if len(forms) != expected:
                            raise ValueError(
                                f"wrong plural form count (expected {expected}, found {len(forms)}): "
                                f"{source[:80]}")
                    for form in forms:
                        value = "".join(form.itertext())
                        if not value.strip():
                            raise ValueError(f"empty finished translation: {source[:80]}")
                        if Counter(PLACEHOLDER.findall(source)) != Counter(PLACEHOLDER.findall(value)):
                            raise ValueError(f"changed placeholders: {source[:80]}")
                        if re.search(r"</?(?:a|b|br|div|em|h[1-6]|i|li|p|span|strong|table|ul)\b", source):
                            original, translated = Markup(source), Markup(value)
                            if original.tags != translated.tags or original.links != translated.links:
                                raise ValueError(f"changed rich-text structure or link: {source[:80]}")
                    finished += 1
            if seen != source_keys:
                raise ValueError("catalog differs from English template; run pvt_update_translations")
            coverage[code] = (finished, total)
            print(f"{path.name}: {finished}/{total} finished")
        except (ET.ParseError, ValueError) as error:
            errors.append(f"{path.name}: {error}")
    for locale in release_locales:
        if locale not in coverage:
            errors.append(f"released locale has no valid catalog: {locale}")
            continue
        finished, total = coverage[locale]
        if finished != total:
            errors.append(
                f"released locale is incomplete: {locale} ({finished}/{total} finished)")
        try:
            errors.extend(f"released locale {locale}: {error}"
                          for error in platform_metadata_errors(locale))
        except (OSError, ET.ParseError) as error:
            errors.append(f"released locale {locale}: platform metadata check failed: {error}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    checker = sub.add_parser("check", help="validate catalogs and report coverage")
    checker.add_argument("--lupdate", help="also check extraction warnings and source freshness")
    sub.add_parser("labels", help="refresh extractable renderer display labels")
    add = sub.add_parser("add", help="create unfinished catalogs for one or more Qt locales")
    add.add_argument("locales", nargs="+", help="Qt locale(s), e.g. fr, pt_BR, zh_TW, sr_Latn")
    add.add_argument("--lupdate", default=shutil.which("lupdate"))
    args = parser.parse_args()
    if args.command == "check":
        return check(args.lupdate)
    if args.command == "labels":
        (ROOT / "gui/renderer_labels.h").write_text(renderer_labels(), encoding="utf-8")
        return 0
    if any(not LOCALE_CODE.fullmatch(locale)
           for locale in args.locales):
        parser.error("use Qt locale codes with underscores")
    if len(set(args.locales)) != len(args.locales):
        parser.error("each locale may be listed only once")
    if not args.lupdate:
        parser.error("pass --lupdate /path/to/Qt/bin/lupdate")
    try:
        add_catalogs(args.locales, args.lupdate)
    except ValueError as error:
        parser.error(str(error))
    print("Catalogs ready. Translate with Qt Linguist, then reconfigure/build; no language registry edits needed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
